name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: âš™ï¸ Setup Node.js for Percy CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent stable version

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/java-8/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/java-8/
      - run: make install

      - name: ğŸ“¸ Install CLI and Run Tests with Percy
        run: |
          npm install --save-dev @percy/cli
          npx percy exec -- make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
